### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by BunyaminEfe** [PKU-MARL/DexterousHands#14]
![ex](https://user-images.githubusercontent.com/30906513/198411612-a766784f-85bf-4334-a0cf-926cd917a9da.png)
Why am I getting this error you see?
python3 joint_monkey.py command works fine. isaacGYM works fine

**Comment by cypypccpy** [comment]
Dear @BunyaminEfe ,

This is always due to a mismatch between the pytorch version and your GPU cuda driver:
![198411612-a766784f-85bf-4334-a0cf-926cd917a9da](https://user-images.githubusercontent.com/55881363/198430038-b9536894-e2c3-49d8-bca4-a0ceb0fb1a96.png)

According to the above error message, you can try to improve the pytorch version corresponding to the cuda driver.

Hope this can help you.

**Comment by BunyaminEfe** [comment]
![sor2](https://user-images.githubusercontent.com/30906513/198575614-e7750657-4c04-4d87-bbb0-55e7ba6a3adb.png)
English version of the fault text in the last line
`Parçalama arızası (çekirdek döküldü) = Shredding failure (core spilled)` What is the solution of the line here?

**Comment by cypypccpy** [comment]
Hi @BunyaminEfe ,

This may be because of this line that reports the error:
```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```
I found a [post similar to your error](https://forums.developer.nvidia.com/t/whats-the-minimum-gpu-configuration-to-use-isaac-gym/197681) on the official forum of Isaac gym, You might be able to refer to the answer in it:
![image](https://user-images.githubusercontent.com/55881363/198577864-335e129e-2354-4e65-a32a-bdfbe3ecbc8a.png)

Anyway, since Isaac Gym is still in development, empirically it will have kinds of issues. Sometimes I also look for answers on the official forums I mentioned above, which are very helpful.

Hope this can help you.

**Comment by BunyaminEfe** [comment]
Upgrading version 520 was not a solution unfortunately @cypypccpy

**Comment by BunyaminEfe** [comment]
i solved that problem but now i am facing this problem
![sor3](https://user-images.githubusercontent.com/30906513/198651668-7dc384b9-04df-475d-a757-2eaaca6ad652.png)

**Comment by cypypccpy** [comment]
Oh, we have also encountered this problem before. It seems that you are using Cloud Container, Our experience suggests that Isaac Gym doesn't seem to support this well, so we solved it by switching to Cloud Hosting.

**Comment by BunyaminEfe** [comment]
@cypypccpy I am not using Cloud Container. My computer is giving the error right now.

**Comment by cypypccpy** [comment]
How about these post? These errors are very similar to yours, I don't know if it helps: [https://forums.developer.nvidia.com/t/weird-bug/210419](https://forums.developer.nvidia.com/t/weird-bug/210419), [https://forums.developer.nvidia.com/t/cuda-and-driver-version/209140](https://forums.developer.nvidia.com/t/cuda-and-driver-version/209140), [https://forums.developer.nvidia.com/t/ubuntu-20-04-libpython3-7m-so-1-0-error-segmentation-fault/163948](https://forums.developer.nvidia.com/t/ubuntu-20-04-libpython3-7m-so-1-0-error-segmentation-fault/163948)

![image](https://user-images.githubusercontent.com/55881363/198837816-e46ec765-dfa7-4000-8ac8-50e11a8d35eb.png)

Or you can try to use this my setting that works well, maybe 520 has some problems because it is too new：
![image](https://user-images.githubusercontent.com/55881363/198838129-038cc864-da43-465e-a0a4-f27f2970333f.png)

**Comment by BunyaminEfe** [comment]
I updated it to version 520 because it gave error on version 470 but it's still the same
![nvidia-smi](https://user-images.githubusercontent.com/30906513/198874502-c19113b2-7f68-434a-83c0-36c3422dac6e.png)

**Comment by cypypccpy** [comment]
Hi @BunyaminEfe ,

I'm so sorry that I couldn't solve your problem, but we and some other people use bi-dexhands well in different computer environments, so I think it may not be a problem with the code. Maybe you can go to the official NVIDIA forum and ask a question about this issue, or try another computer.

**Comment by BunyaminEfe** [comment]
Hi @cypypccpy ,
Thanks for your help. I wish you well in the project you are developing. :)

**Comment by qinge0** [comment]
Do we need to use cuda when configuring the environment for this project?
